### ISSUE TITLE
Commands' help pages seem to be broken

### ISSUE THREAD

**Issue by DavidMarchant** [alces-software/inventoryware#36]
```
[root@localhost inventoryware]# ./lib/inventoryware.rb render --help
/tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/help_formatters/terminal.rb:15:in `read': No such file or directory @ rb_sysopen - /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/help_formatters/terminal/command_help.erb (Errno::ENOENT)
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/help_formatters/terminal.rb:15:in `template'
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/help_formatters/terminal.rb:11:in `render_command'
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/runner.rb:312:in `block (2 levels) in create_default_commands'
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/command.rb:182:in `call'
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/command.rb:153:in `run'
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/runner.rb:57:in `block in run!'
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/runner.rb:400:in `block in global_option_proc'
        from /root/.rbenv/versions/2.5.1/lib/ruby/2.5.0/optparse.rb:1552:in `block in parse_in_order'
        from /root/.rbenv/versions/2.5.1/lib/ruby/2.5.0/optparse.rb:1538:in `catch'
        from /root/.rbenv/versions/2.5.1/lib/ruby/2.5.0/optparse.rb:1538:in `parse_in_order'
        from /root/.rbenv/versions/2.5.1/lib/ruby/2.5.0/optparse.rb:1532:in `order!'
        from /root/.rbenv/versions/2.5.1/lib/ruby/2.5.0/optparse.rb:1626:in `permute!'
        from /root/.rbenv/versions/2.5.1/lib/ruby/2.5.0/optparse.rb:1648:in `parse!'
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/runner.rb:381:in `parse_global_options'
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/runner.rb:65:in `run!'
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/delegates.rb:15:in `run!'
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/import.rb:5:in `block in <top (required)>'
[root@localhost inventoryware]# ./lib/inventoryware.rb parse --help
/tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/help_formatters/terminal.rb:15:in `read': No such file or directory @ rb_sysopen - /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/help_formatters/terminal/command_help.erb (Errno::ENOENT)
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/help_formatters/terminal.rb:15:in `template'
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/help_formatters/terminal.rb:11:in `render_command'
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/runner.rb:312:in `block (2 levels) in create_default_commands'
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/command.rb:182:in `call'
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/command.rb:153:in `run'
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/runner.rb:57:in `block in run!'
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/runner.rb:400:in `block in global_option_proc'
        from /root/.rbenv/versions/2.5.1/lib/ruby/2.5.0/optparse.rb:1552:in `block in parse_in_order'
        from /root/.rbenv/versions/2.5.1/lib/ruby/2.5.0/optparse.rb:1538:in `catch'
        from /root/.rbenv/versions/2.5.1/lib/ruby/2.5.0/optparse.rb:1538:in `parse_in_order'
        from /root/.rbenv/versions/2.5.1/lib/ruby/2.5.0/optparse.rb:1532:in `order!'
        from /root/.rbenv/versions/2.5.1/lib/ruby/2.5.0/optparse.rb:1626:in `permute!'
        from /root/.rbenv/versions/2.5.1/lib/ruby/2.5.0/optparse.rb:1648:in `parse!'
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/runner.rb:381:in `parse_global_options'
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/runner.rb:65:in `run!'
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/delegates.rb:15:in `run!'
        from /tmp/inventoryware/vendor/ruby/2.5.0/gems/commander-4.4.7/lib/commander/import.rb:5:in `block in <top (required)>'
[root@localhost inventoryware]# ./lib/inventoryware.rb  --help
  NAME:

    Inventoryware

  DESCRIPTION:

    Parser of hardware information into unified formats.

  COMMANDS:
        
    edit   Edit some nodes' data                
    help   Display global or [command] help documentation               
    parse  Parse hardware information into yaml         
    render Render nodes' data as an eRuby template      

  GLOBAL OPTIONS:
        
    -h, --help
        Display help documentation
        
    -v, --version
        Display version information
        
    -t, --trace
        Display backtrace when an error occurs
        
[root@localhost inventoryware]# 
```

**Comment by DavidMarchant** [comment]
On further investigation this issue appears to be exclusive to my machine - I'll close it for now and potentially reopen in future.
